/**
 * src/js/mv3/dnr-priority-policy.ts
 *
 * Static priority bands for DNR rules. Every rule generated by
 * the extension must fall into one of these bands. The policy
 * prevents subtle rule-order bugs before the compiler starts
 * producing real rules.
 *
 * Higher numeric priority wins in DNR. Each band reserves a
 * contiguous, non-overlapping integer range.
 */

export type DnrPriorityBandName =
  | 'codeViewerDiagnostic'
  | 'userEmergencyOverride'
  | 'sessionTemporary'
  | 'userPersistentSafeDynamic'
  | 'userManagedReserved'
  | 'userDisabledStaticReplacement'
  | 'packagedImportantAllow'
  | 'packagedImportantBlock'
  | 'packagedAllow'
  | 'packagedHighConfidenceBlock'
  | 'packagedTrackerPrivacy'
  | 'packagedAnnoyance'
  | 'upgradeScheme'
  | 'experimentalPackaged';

export type DnrPriorityRange = readonly [number, number];

export const DNR_PRIORITY_BANDS: Readonly<Record<DnrPriorityBandName, DnrPriorityRange>> = {
  codeViewerDiagnostic: [2_500_000, 2_599_999],
  userEmergencyOverride: [2_400_000, 2_499_999],
  sessionTemporary: [2_300_001, 2_399_999],
  userPersistentSafeDynamic: [2_200_001, 2_300_000],
  userManagedReserved: [700000, 799999],
  userDisabledStaticReplacement: [600000, 699999],
  packagedImportantAllow: [580000, 599999],
  packagedImportantBlock: [550000, 579999],
  packagedAllow: [500000, 539999],
  packagedHighConfidenceBlock: [400000, 449999],
  packagedTrackerPrivacy: [300000, 399999],
  packagedAnnoyance: [200000, 299999],
  upgradeScheme: [100000, 199999],
  experimentalPackaged: [1, 99999],
} as const;

export function getPriorityBand(
    priority: number,
): DnrPriorityBandName | null {
    if (!Number.isInteger(priority)) return null;
    for (const name of Object.keys(DNR_PRIORITY_BANDS) as DnrPriorityBandName[]) {
        const [lo, hi] = DNR_PRIORITY_BANDS[name];
        if (priority >= lo && priority <= hi) return name;
    }
    return null;
}

export interface BandAssertion {
  ok: boolean;
  reason: string;
}

export function assertPriorityInBand(
    priority: number,
    band: DnrPriorityBandName,
): BandAssertion {
    const range = DNR_PRIORITY_BANDS[band];
    if (!range) {
        return { ok: false, reason: `Unknown band: ${band}` };
    }
    const [lo, hi] = range;
    if (!Number.isInteger(priority) || priority < lo || priority > hi) {
        return {
      ok: false,
      reason: `Priority ${priority} not in band ${band} [${lo}, ${hi}].`,
        };
    }
    return { ok: true, reason: `Priority ${priority} is in band ${band}.` };
}

export interface BandOverlapReport {
  ok: boolean;
  overlaps: Array<{ a: DnrPriorityBandName; b: DnrPriorityBandName; range: DnrPriorityRange }>;
}

export function assertNoBandOverlap(): BandOverlapReport {
    const names = Object.keys(DNR_PRIORITY_BANDS) as DnrPriorityBandName[];
    const overlaps: BandOverlapReport['overlaps'] = [];
    for (let i = 0; i < names.length; i++) {
        for (let j = i + 1; j < names.length; j++) {
            const a = names[i];
            const b = names[j];
            const [aLo, aHi] = DNR_PRIORITY_BANDS[a];
            const [bLo, bHi] = DNR_PRIORITY_BANDS[b];
            if (aLo <= bHi && bLo <= aHi) {
        overlaps.push({ a, b, range: [Math.max(aLo, bLo), Math.min(aHi, bHi)] });
            }
        }
    }
    return { ok: overlaps.length === 0, overlaps };
}
