export type DiagnosticSeverity = 'info' | 'warning' | 'error'

export interface Diagnostic {
  code: string
  message: string
  severity: DiagnosticSeverity
  path?: string
  hint?: string
}

export function diagnostic(
    code: string,
    message: string,
    severity: DiagnosticSeverity = 'error',
    hint?: string,
): Diagnostic {
    return { code, message, severity, hint }
}

export const DIAGNOSTIC_CODES = {
  TARGET_INVALID: 'target-invalid',
  TARGET_REGEX_UNSAFE: 'target-regex-unsafe',
  PATH_INVALID: 'path-invalid',
  PATH_REGEX_UNSAFE: 'path-regex-unsafe',
  MISSING_SCOPE: 'missing-scope',
  UNSAFE_SCOPE_SELECTOR: 'unsafe-scope-selector',
  CANDIDATE_UNSAFE_SELECTOR: 'candidate-unsafe-selector',
  CANDIDATE_REQUIRED: 'candidate-required',
  SCOPE_IS_BODY: 'scope-is-body',
  BOUNDARY_INVALID: 'boundary-invalid',
  BOUNDARY_MODE_MISMATCH: 'boundary-mode-mismatch',
  BOUNDARY_CROSS_SCOPE_CONFLICT: 'boundary-cross-scope-conflict',
  MATCH_MODE_NONE_WITH_THRESHOLD: 'threshold-with-mode-none',
  MATCH_MODE_NONE_WITH_REFERENCE: 'reference-with-mode-none',
  MATCH_MODE_NONE_WITH_WEIGHTS: 'weights-with-mode-none',
  MATCH_MODE_EXACT_WITH_THRESHOLD: 'threshold-with-exact-mode',
  MATCH_SIMILAR_WITHOUT_REFERENCE: 'similar-without-reference',
  MATCH_STRUCTURAL_WITHOUT_REFERENCE: 'structural-without-reference',
  MATCH_WEAK_EXACT_REFERENCE: 'weak-exact-reference',
  MATCH_MISSING_REFERENCE: 'missing-match-reference',
  WEIGHTS_INVALID_PROFILE: 'weights-invalid-profile',
  ACTION_SMART_ALLOW_INVALID: 'smart-allow-invalid-action',
  ACTION_REMOVE_WARNING: 'action-remove-warning',
  WHERE_MISSING_SMART: 'where-missing-smart',
  LOGIC_INVALID: 'logic-invalid',
  KEYWORDS_INACTIVE: 'keywords-inactive',
  KEYWORDS_IGNORED_BY_EXPLICIT_LOGIC: 'keywords-ignored-by-explicit-logic',
  KEYWORD_MERGE_CONFLICT: 'keyword-merge-conflict',
  REGEX_UNSUPPORTED_FLAG: 'regex-unsupported-flag',
  REGEX_UNCOMPILABLE: 'regex-uncompilable',
  REGEX_BUDGET_RISK: 'regex-budget-risk',
  REGEX_BUDGET_EXCEEDED: 'regex-budget-exceeded',
  REGEX_INPUT_TRUNCATED: 'regex-input-truncated',
  UNSAFE_REGEX: 'unsafe-regex',
  SAFETY_MIN_FEATURES_MODE_NONE: 'min-features-mode-none',
  SAFETY_MIN_LOGIC_MATCHES_IMPOSSIBLE: 'min-logic-matches-impossible',
  SAFETY_PREVIEW_REQUIRED: 'preview-required',
  SAFETY_PREVIEW_NOT_CONFIRMED: 'preview-not-confirmed',
  PERFORMANCE_INVALID: 'performance-invalid',
  FRAMES_INVALID: 'frames-invalid',
  SHADOW_INVALID: 'shadow-invalid',
  UNSAFE_SHADOW_SELECTOR: 'unsupported-shadow-selector',
  RUNTIME_INVALID: 'runtime-invalid',
  BROAD_RULE_WARNING: 'broad-rule-warning',
  BROAD_EXACT_SCOPE: 'broad-exact-scope',
  ALLOW_BROAD_REQUIRED: 'allow-broad-required',
  LOW_SIMILARITY_THRESHOLD: 'low-similarity-threshold',
  EXACT_MODE_SELECTOR_REQUIRED: 'exact-mode-selector-required',
  IMPORT_COLLISION: 'import-collision',
  IMPORT_SYNTAX_VERSION_UNSUPPORTED: 'syntax-version-unsupported',
  EXPORT_LOSS: 'export-loss',
  DEPRECATED_FIELD: 'deprecated-field',
  UNSUPPORTED_COMPOSITION: 'unsupported-composition-field',
  BOUNDARY_REQUIRED: 'boundary-required',
  EXACT_HIDE_BROAD_BOUNDARY: 'exact-hide-broad-boundary',
  ORIGINAL_SYNTAX_MISMATCH: 'original-syntax-mismatch',
  ALLOW_BROAD_EXPECTED: 'allow-broad-expected',
  STYLE_VAR_NOT_ALLOWED: 'style-var-not-allowed',
  REGEX_STATIC_REJECTED: 'regex-static-rejected',
  REGEX_TOO_LONG: 'regex-too-long',
  CATCH_ALL_ALLOW: 'catch-all-allow',
  MISSING_CANDIDATES: 'missing-candidates',
  MISSING_BOUNDARY: 'missing-boundary',
  UNSAFE_CANDIDATE_SELECTOR: 'unsafe-candidate-selector',
  AMBIGUOUS_REFERENCE_FIRST_USED: 'ambiguous-reference-first-used',
  REFERENCE_SELECTION_UNUSED: 'reference-selection-unused',
  EXTERNAL_FILTERS_NOT_SIMULATED: 'external-filters-not-simulated',
  EXTERNAL_FILTER_OVERRIDE_SMART_ALLOW: 'external-filter-overrode-smart-allow',
  WEAK_EXACT_REFERENCE_WARN: 'weak-exact-reference-warn',
  ALLOW_PAGE_ROOT_WITHOUT_CONFIRM: 'allow-page-root-without-confirm',
  INCLUDE_SELF_NOT_SELECTOR_MODE: 'include-self-not-selector-mode',
  KEYWORD_WORD_BOUNDARY_IGNORED: 'keyword-word-boundary-ignored',
  UNSUPPORTED_NEW_SYNTAX: 'unsupported-new-syntax',
  CUSTOM_WEIGHTS_NOT_SUPPORTED_V1: 'custom-weights-not-supported-v1',
  INVALID_RULE_ACTION_COMBINATION: 'invalid-rule-action-combination',
  ALLOW_SCOPE_ROOT_WITHOUT_STOP: 'allow-scope-root-without-stop',
  WORD_BOUNDARY_REDUNDANT: 'word-boundary-redundant',
  STYLE_FILTER_PERCENTAGE: 'style-filter-percentage',
  MATCH_MODE_NONE_NO_WHERE: 'match-mode-none-no-where',
  MATCH_MODE_SMART_ALLOW_INVALID: 'match-mode-smart-allow-invalid',
  INVALID_BOUNDARY_DEPTH: 'invalid-boundary-depth',
  DEPENDENCY_DEPTH_MAY_MISS_DESCENDANT: 'dependency-depth-may-miss-descendant',
  SCOPE_ROOT_TOO_LARGE: 'scope-root-too-large',
  SELECTOR_BOUNDARY_NOT_FOUND: 'selector-boundary-not-found',
  BOUNDARY_LOW_CONFIDENCE: 'boundary-low-confidence',
  FRAME_INACCESSIBLE: 'frame-inaccessible',
  PARTIAL_SHADOW_DISCOVERY: 'partial-shadow-discovery',
  CANDIDATE_BUDGET_EXCEEDED: 'candidate-budget-exceeded',
  EXTERNAL_REMOVE_NOT_RESTORABLE: 'external-remove-not-restorable',
  IMPORTANT_IGNORED_FOR_BUILT_IN: 'important-ignored-for-built-in',
  MIN_FEATURES_UNUSED_EXACT: 'min-features-unused-exact',
  MIN_FEATURES_INVALID_WITH_NONE: 'min-features-invalid-with-none',
  INVALID_KEYWORD_WORD_MODE: 'invalid-keyword-word-mode',
  THRESHOLD_NOT_VALID_FOR_MODE_NONE: 'threshold-not-valid-for-mode-none',
} as const

export function diagnosticsFromErrors(errors: string[]): Diagnostic[] {
    return errors.map(msg => diagnostic('validation-error', msg, 'error'))
}
